name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 깃허브에서 코드 가져오기
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 2. 자바 17 환경 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 빌드 (테스트 생략)
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      # 4. 도커 허브 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. 도커 이미지 빌드 & 푸시
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/arto-be:latest

      # 6. EC2에 접속해서 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 1. 기존 컨테이너 중지 및 삭제 (에러 무시)
            sudo docker stop arto-server || true
            sudo docker rm arto-server || true
            
            # 2. 불필요한 이미지 정리
            sudo docker image prune -f
            
            # 3. 최신 이미지 다운로드
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/arto-be:latest
            
            
            sudo docker run -d --name arto-server -p 8080:8080 \
              -e SPRING_DATASOURCE_URL='${{ secrets.DB_URL }}' \
              -e SPRING_DATASOURCE_USERNAME='${{ secrets.DB_USERNAME }}' \
              -e SPRING_DATASOURCE_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              ${{ secrets.DOCKER_USERNAME }}/arto-be:latest